Implemented Hash_reputation and get_threat_notes actions
metron-labs/phantom-apps pull request #22
Opened 2021-10-06 09:59 UTC by abhijeeta-metron

2021-10-07 07:50 UTC, devang-metron requested changes

2021-10-07 07:50 UTC, devang-metron commented on Apps/phsentinelone/sentinelone_connector.py
> +            return action_result.set_status(phantom.APP_ERROR, "Did not get proper response from the server")
site id param is not required, remove it

2021-10-07 07:50 UTC, devang-metron commented on Apps/phsentinelone/sentinelone_connector.py
> +        s1_threat_ids = param['s1_threat_ids']
Isn't ids are in form of array?

2021-10-07 07:50 UTC, devang-metron commented on Apps/phsentinelone/sentinelone_connector.py
> +                            "ids": s1_threat_ids,
You have to added multiple threats in form of array and not just string

2021-10-07 12:53 UTC, abhijeeta-metron commented on Apps/phsentinelone/sentinelone_connector.py
> +        s1_threat_ids = param['s1_threat_ids']
yes

2021-10-07 12:53 UTC, abhijeeta-metron commented on Apps/phsentinelone/sentinelone_connector.py
> +                            "ids": s1_threat_ids,
Data type of ids is an array

2021-10-08 08:10 UTC, devang-metron approved these changes

2021-10-08 08:13 UTC, devang-metron requested changes

2021-10-08 08:13 UTC, devang-metron commented on Apps/phsentinelone/sentinelone_connector.py
> +        elif action_id == 'add_note':
add_note doesn't depict to which thing to add note to.

2021-10-08 08:13 UTC, devang-metron commented on Apps/phsentinelone/sentinelone_connector.py
> +        elif action_id == 'add_note':
also change function name _handle_add_note for the same.

2021-10-08 08:32 UTC, devang-metron approved these changes

2021-10-08 08:32 UTC, merged